import React, { useState } from 'react';
import { 
  ShieldAlert, 
  PhoneCall, 
  Lock, 
  Download, 
  UserCheck,
  X
} from 'lucide-react';
import { soundFx } from '../utils/audio';
import { triggerHaptic } from '../utils/haptics';

interface EmergencyShieldModalProps {
  isOpen: boolean;
  onClose: () => void;
  detectedThreat?: string;
}

export const EmergencyShieldModal: React.FC<EmergencyShieldModalProps> = ({
  isOpen,
  onClose,
  detectedThreat = "Covert Pinhole IP Camera (Tuya Board, Port 554 RTSP)"
}) => {
  const [evidenceSaved, setEvidenceSaved] = useState(false);

  if (!isOpen) return null;

  const downloadForensicLog = () => {
    setEvidenceSaved(true);
    triggerHaptic('heavy');
    soundFx.playSuccessChime();

    const logContent = `
SPYZERO FORENSIC INCIDENT LOG
------------------------------------------------------
Timestamp: ${new Date().toISOString()}
Classification: UNLAWFUL COVERT SURVEILLANCE DETECTED
Device Type: ${detectedThreat}
Network Subnet: 192.168.1.0/24
Open Streaming Ports: 554 (RTSP), 8080 (MJPEG)
Digital Hash: SZ-FORENSIC-${Math.random().toString(36).substring(2, 10).toUpperCase()}

CHAIN OF CUSTODY INSTRUCTIONS:
1. Do not clean or touch the suspect lens (preserves fingerprints).
2. Photograph the device from multiple angles.
3. Present this timestamped record to local police / hotel authority.
------------------------------------------------------
Generated by SpyZero Mobile Room Guard.
    `;
    const blob = new Blob([logContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SpyZero-Evidence-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleClose = () => {
    triggerHaptic('light');
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex flex-col justify-end sm:justify-center items-center p-0 sm:p-4 overflow-y-auto">
      {/* Mobile Bottom Sheet Card */}
      <div className="bg-zinc-900 border-t sm:border border-zinc-800 rounded-t-3xl sm:rounded-2xl max-w-md w-full p-5 sm:p-6 shadow-2xl space-y-4 max-h-[90vh] overflow-y-auto pb-8 sm:pb-6 animate-in slide-in-from-bottom duration-200 text-zinc-100">
        
        {/* Mobile Drag Pill */}
        <div className="w-12 h-1 bg-zinc-700 rounded-full mx-auto -mt-1 mb-2" />

        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-zinc-800 pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-red-600/20 text-red-400 flex items-center justify-center">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-white leading-tight">
                Emergency Privacy Checklist
              </h2>
              <span className="text-[11px] text-red-400 font-medium">
                Suspicious Surveillance Device Flagged
              </span>
            </div>
          </div>

          <button
            onClick={handleClose}
            className="p-1.5 rounded-lg bg-zinc-800 text-zinc-400 hover:text-white hover:bg-zinc-750 transition"
            title="Close Alert"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Threat Banner */}
        <div className="bg-red-950/30 border border-red-800/60 rounded-xl p-3">
          <div className="text-xs font-medium text-red-300">
            Detected Device Identifier:
          </div>
          <div className="text-xs text-zinc-300 font-mono mt-0.5 break-all">
            {detectedThreat}
          </div>
        </div>

        {/* 4 Emergency Steps */}
        <div className="space-y-2 text-xs">
          <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl flex items-start space-x-3">
            <span className="w-5 h-5 rounded-full bg-zinc-800 text-zinc-300 border border-zinc-700 font-semibold flex items-center justify-center shrink-0 text-[11px]">
              1
            </span>
            <div>
              <strong className="text-zinc-100 block">Do Not Touch the Lens</strong>
              <p className="text-zinc-400 text-[11px] mt-0.5 leading-relaxed">
                Touching the aperture wipes fingerprints. Leave the hardware intact for official verification.
              </p>
            </div>
          </div>

          <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl flex items-start space-x-3">
            <span className="w-5 h-5 rounded-full bg-zinc-800 text-zinc-300 border border-zinc-700 font-semibold flex items-center justify-center shrink-0 text-[11px]">
              2
            </span>
            <div>
              <strong className="text-zinc-100 block">Cover the Camera Aperture</strong>
              <p className="text-zinc-400 text-[11px] mt-0.5 leading-relaxed">
                Cover the suspect opening with an adhesive band, sticker, or place an opaque object in front of it.
              </p>
            </div>
          </div>

          <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl flex items-start space-x-3">
            <span className="w-5 h-5 rounded-full bg-zinc-800 text-zinc-300 border border-zinc-700 font-semibold flex items-center justify-center shrink-0 text-[11px]">
              3
            </span>
            <div className="flex-1">
              <strong className="text-zinc-100 block">Save Evidence Report</strong>
              <p className="text-zinc-400 text-[11px] mt-0.5 leading-relaxed">
                Save a timestamped record to show hotel management or authorities.
              </p>
              <button
                onClick={downloadForensicLog}
                className="mt-2 w-full sm:w-auto px-3 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-medium flex items-center justify-center space-x-1.5 transition active:scale-95"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{evidenceSaved ? '✓ Evidence Downloaded' : 'Save Incident Log'}</span>
              </button>
            </div>
          </div>

          <div className="p-3 bg-zinc-950 border border-zinc-800 rounded-xl flex items-start space-x-3">
            <span className="w-5 h-5 rounded-full bg-zinc-800 text-zinc-300 border border-zinc-700 font-semibold flex items-center justify-center shrink-0 text-[11px]">
              4
            </span>
            <div>
              <strong className="text-zinc-100 block">Report to Front Desk</strong>
              <p className="text-zinc-400 text-[11px] mt-0.5 leading-relaxed">
                Do not confront staff alone in the room. Quietly gather your belongings and head to the lobby.
              </p>
            </div>
          </div>
        </div>

        {/* Emergency Hotlines */}
        <div className="pt-2 border-t border-zinc-800">
          <div className="text-[11px] font-medium text-zinc-400 mb-2">
            Emergency Hotlines:
          </div>
          <div className="grid grid-cols-3 gap-2 text-center text-xs">
            <a
              href="tel:112"
              onClick={() => triggerHaptic('heavy')}
              className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 hover:bg-zinc-850 text-zinc-200 transition flex flex-col items-center active:scale-95"
            >
              <PhoneCall className="w-4 h-4 text-red-400 mb-1" />
              <span className="font-semibold text-sm">112</span>
              <span className="text-[10px] text-zinc-400">Police</span>
            </a>

            <a
              href="tel:1091"
              onClick={() => triggerHaptic('heavy')}
              className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 hover:bg-zinc-850 text-zinc-200 transition flex flex-col items-center active:scale-95"
            >
              <UserCheck className="w-4 h-4 text-purple-400 mb-1" />
              <span className="font-semibold text-sm">1091</span>
              <span className="text-[10px] text-zinc-400">Helpline</span>
            </a>

            <a
              href="tel:1930"
              onClick={() => triggerHaptic('heavy')}
              className="p-2.5 rounded-xl bg-zinc-950 border border-zinc-800 hover:bg-zinc-850 text-zinc-200 transition flex flex-col items-center active:scale-95"
            >
              <Lock className="w-4 h-4 text-blue-400 mb-1" />
              <span className="font-semibold text-sm">1930</span>
              <span className="text-[10px] text-zinc-400">Cyber Cell</span>
            </a>
          </div>
        </div>

      </div>
    </div>
  );
};
